default: clack

clack: clac.c clac_file.h clac_string.h clac_types.h clac_utils.h clac_scanner.h
	gcc -Wall -std=c99 clac.c clac_file.h clac_string.h clac_types.h clac_utils.h clac_scanner.h -lm -o clack